### PR TITLE
WIP: Add Three.js Journey examples

### PR DESCRIPTION
**Pull request by hazem3500**
- [x] Init Next.js
- [x] Add **Basics** examples
- [x] Add **Classic Techniques** examples
- [x] Add **Advanced Techniques** examples
- [x] Add **Shaders** examples
- [x] Add **Extra** examples
- [x] Add **Stage 1** example ([link](https://codesandbox.io/s/threejs-journey-level-1-kheke))
- [x] Add page titles to each page
- [x] Add home page to view all examples

### CODE REVIEW

**Comment by hazem3500** [comment]
Hey @drcmda 👋
I've added all the examples and did a basic home page for now, there are other stuff that I'd like to add (added separate issues on the repo for them)
But I'll be AFK for the next 4-5 days 😅, so I'll continue when I get back, just thought I'd notify you so you don't think the PR has gone stale XD

If anyone ones to continue while I'm AFK, I've added issues on what's left.

**Comment by drcmda** [comment]
should we merge and set up the vercel backend? doesnt have to be all in one pr, this is great!"

**Comment by hazem3500** [comment]
> should we merge and set up the vercel backend? doesnt have to be all in one pr, this is great!"

Yup, we can merge 😁

**Comment by drcmda** [comment]
@hazem3500 its wired into https://journey.pmnd.rs could we get a little button or something that leads to the source of each demo for easier lookup? also something that leads to the original bruno simon journey course?

**Comment by hazem3500** [comment]
Yup, I've created an issue for it #5

Will be able to do it once I'm back though 😅

**Pull request merged**
